### ISSUE TITLE
Convert all .pdf figures to .eps

### ISSUE THREAD

**Issue by mjuric** [mjuric/adass-2015-paper#18]
That's what's required for submission. [U+1F922](http://emojipedia.org/nauseated-face/).

**Comment by timj** [comment]
For reference: http://www.caastro.org/adass-xxv---proceedings-instructions

<blockquote>
Figures (in encapsulated PostScript format) should be named <paper_ID>_fn.eps where n is the figure number, e.g. P030_f1.eps.
</blockquote>

**Comment by timj** [comment]
See #24 although it's probably a good idea to also get the updated figure from @yalsayyad

**Comment by timj** [comment]
Note that the files need to be renamed for submission.

**Comment by mjuric** [comment]
If it'd make any difference, sure, but if this one looks OK (can't tell yet, git's been downloading the new stuff for >5 minutes now... airplane wifi, grr...) there's no need to go through the trouble.

**Comment by mjuric** [comment]
OK, will do the renames.
