### ISSUE TITLE
Double citing of SDSS

### ISSUE THREAD

**Issue by timj** [mjuric/adass-2015-paper#20]
On page 7 section 4 we cite "SDSS (York et al)" and then towards the bottom of the page we say "SDSS (Abazajian et al. 2009)". Seems weird to do that. I think I'd prefer either we drop the second or we add it to the first mention.

**Comment by mjuric** [comment]
Good points, but I'm my solution will just make it worse :).
- The first reference is in the context of the technical design + plan of the survey, so York is most appropriate
- The second time I cite it I specifically refer to DR7 so Abazajian et al. is appropriate
- And the third time I mention it, I refer to it in the context of the imaging data we used for reprocessing, so actually the DR9 paper (Ahn et al.) is the right one to cite there.
