### ISSUE TITLE
Add ref to MOPSIAU paper

### ISSUE THREAD

**Issue by timj** [mjuric/adass-2015-paper#22]
In commit 03d7cdda151284737518eea81340d4d29c9bae31 we replaced a link to the (non-existant) MOPS IAU paper with a ref to LDM-156. The paper has now been placed on arXiv as http://arxiv.org/abs/1511.03199

Should we now add this reference or is it okay to leave it simply pointing at LDM-156? Should it replace LDM-156?

**Comment by mjuric** [comment]
Fixed in 36377d8. I referred to it at the point where we first mention LDM-156, but not the second time (where I was listing the pipeline design documents).
