### ISSUE TITLE
Broken references

### ISSUE THREAD

**Issue by jdswinbank** [mjuric/adass-2015-paper#9]
```
Citation `MOPSIAU' on page 7 undefined on input line 33
Reference `sec:imsim' on page 5 undefined on input line 281.
Reference `Sec:minisurveys' on page 8 undefined on input line 38
```

**Comment by timj** [comment]
Yes, I have no idea what @mjuric had in mind there otherwise I'd fix them.

**Comment by jdswinbank** [comment]
Likewise -- I was going to fix them in my PR, but then realised I didn't know how.

**Comment by mjuric** [comment]
Thanks for pointing those out -- I'll need to fix them (the first will point to Jones & Juric paper from the IAU, the second two to sections in the Overview paper). Trying to get to these sometime tomorrow.

**Comment by timj** [comment]
On ADS I can only find a Juric, Jones, Axelrod and Ivezic paper from this year: http://adsabs.harvard.edu/abs/2015IAUGA..2256348J

I can't find any "Jones and Juric" papers there yet.

**Comment by mjuric** [comment]
It's 'in press' -- I've asked @rhiannonlynne to send me a ref if she already has it.

**Comment by timj** [comment]
Maybe we can also get a copy on arXiv. Can fix up the ref next week once the arXiv identifier becomes known. I was wondering about doing that to my paper as well (given that ADASS papers won't be published until September next year it's always worth uploading to arXiv).

**Comment by mjuric** [comment]
I think all broken refs should be fixed now (please reopen if I missed any). I've temporarily used the MOPS design paper instead of the IAU paper, until we get it on arXiv.
